tab_spaces = 1
brace_style = "AlwaysNextLine"
chain_width = 1
combine_control_expr = false
comment_width = 140
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2018"
enum_discrim_align_threshold = 140
fn_single_line = true
#fn_params_layout = "Vertical"
#fn_call_witdh = 140
force_explicit_abi = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "Vertical"
#match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 140
# merge_imports = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 140
struct_field_align_threshold = 140
struct_lit_single_line = false
#struct_lit_width = 0
struct_variant_width = 0
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
#width_heuristics = "Off"
where_single_line = true
